# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58dc17004dcd130db816d1d8d05f8b0d0ba09b2e226e13b962982ee85db945a645a5cea2778eee3fcba3757451cc449d5e416b61253c0e46b520cb4801502107

test:
  secret_key_base: 765da43047a9a6040e0b52fe359af62179ddeff20f7e8316eff37e92aa3e010617b6a05d9b91ba251c727bbb056c449513ea70a63afb750b983c8c52bf4c313a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
